site_name: 2023.1-Alistamento
site_url: https://interacao-humano-computador.github.io/2023.1-Alistamento/
repo_name: 2023.1-Alistamento
repo_url: https://github.com/Interacao-Humano-Computador/2023.1-Alistamento/
nav:
    - Home: index.md
    - Atas de Reunião:
      - Ata 1: atas/ata1.md
      - Ata 2: atas/ata2.md
      - Ata 3 (Entrega 1): atas/ata3.md
      - Ata 4: atas/ata4.md
      - Ata 5 (Entrega 2): atas/ata5.md
    - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Cronograma Executado: planejamento/cronograma_executado.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Sites avaliados: planejamento/sites_avaliados.md
      - Avaliação dos sites:
        - Alistamento Militar: planejamento/avaliacoes/alistamento.md
        - Escola de Música: planejamento/avaliacoes/escola.md
        - Shopee: planejamento/avaliacoes/shopee.md
        - Striker: planejamento/avaliacoes/striker.md
      - Site escolhido: planejamento/site_escolhido.md
      - Processo de design: planejamento/processo_design.md
    - Análise de Requisitos:
      - Aspectos Éticos: analise_requisitos/aspectos_eticos.md
      - Perfil do Usuário: analise_requisitos/perfil_do_usuario.md
      - Personas: analise_requisitos/personas.md
      - Análise de Tarefas: analise_requisitos/analise_tarefas.md
      - Princípios Gerais do Projeto: analise_requisitos/principios_gerais.md
      - Características da Plataforma: analise_requisitos/caracteristicas.md
      - Metas de Usabilidade: analise_requisitos/metas_usabilidade.md
      - Guia de Estilo: analise_requisitos/guia_estilo.md
    - Design, Avaliação e Desenvolvimento:
      - Nível 1:
        - Análise de Tarefas:
          - Planejamento da Avaliação da Análise de Tarefas: design_avaliacao_desenvolvimento/nivel1/analise_tarefas/planejamento_avaliacao.md 
          - Planejamento do Relato dos Resultados da Análise de Tarefas: design_avaliacao_desenvolvimento/nivel1/analise_tarefas/planejamento_do_relato_dos_resultados.md
          - Relato dos Resultados da Análise de Tarefas: design_avaliacao_desenvolvimento/nivel1/analise_tarefas/relato_resultados.md 
        - Storyboard:
          - Planejamento da Avaliação do Storyboard: design_avaliacao_desenvolvimento/nivel1/storyboard/planejamento_avaliacao.md 
          - Planejamento do Relato dos Resultados do Storyboard: design_avaliacao_desenvolvimento/nivel1/storyboard/planejamento_do_relato_dos_resultados.md
          - Relato dos Resultados do Storyboard: design_avaliacao_desenvolvimento/nivel1/storyboard/relato_resultados.md
          - Storyboards desenvolvidos: design_avaliacao_desenvolvimento/nivel1/storyboard/storyboard.md
      - Nível 2:
        - Planejamento da Avaliação dos Protótipos de Papel: design_avaliacao_desenvolvimento/nivel2/planejamento-avaliacao-prototipo-papel.md
        - Planejamento do Relato dos Resultados dos Protótipos de Papel: design_avaliacao_desenvolvimento/nivel2/planejamento-relato-avaliacao-prototipo-papel.md
        - Protótipos de papel: design_avaliacao_desenvolvimento/nivel2/prototipo_de_papel.md
        - Relato da avaliação doprotótipo de papel: design_avaliacao_desenvolvimento/nivel2/relato_resultados_prototipo_de_papel.md
      - Nível 3:
        - Protótipo de Alta Fidelidade:
          - Planejamento da Avaliação do Protótipo de Alta Fidelidade: design_avaliacao_desenvolvimento/nivel3/planejamento-prototipo-alta-fidelidade.md
          - Planejamento do Relato dos Resultados do Protótipo de Alta Fidelidade: design_avaliacao_desenvolvimento/nivel3/planejamento_relato_alta_fidelidade.md
          - Protótipo de Alta Fidelidade: design_avaliacao_desenvolvimento/nivel3/prototipo_de_alta_fidelidade.md
          - Relato da Avaliação do Protótipo de Alta Fidelidade: design_avaliacao_desenvolvimento/nivel3/relato_alta_fidelidade.md
    - Verificação:
      - Verificação do Grupo 5:
        - Etapa 1:
          - Planejamento da verificação da etapa 1: verificacao/verificacao_5/etapa1/planejamento1.md
          - Verificação dos artefatos da etapa 1: verificacao/verificacao_5/etapa1/verificacao1.md
        - Etapa 2:
          - Planejamento da verificação da etapa 2: verificacao/verificacao_5/etapa2/planejamento2.md
          - Verificação dos artefatos da etapa 2: verificacao/verificacao_5/etapa2/verificacao2.md
        - Etapa 3:
          - Planejamento da verificação da etapa 3: verificacao/verificacao_5/etapa3/planejamento3.md
          - Verificação dos artefatos da etapa 3: verificacao/verificacao_5/etapa3/verificacao3.md
        - Etapa 4:
          - Planejamento da verificação da etapa 4: verificacao/verificacao_5/etapa4/planejamento4.md
          - Verificação dos artefatos da etapa 4: verificacao/verificacao_5/etapa4/verificacao4.md
        - Etapa 5:
          - Planejamento da verificação da etapa 5: verificacao/verificacao_5/etapa5/planejamento5.md
          - Verificação dos artefatos da etapa 5: verificacao/verificacao_5/etapa5/verificacao5.md
      - Verificação do Grupo 6:
        - Etapa 1:
          - Planejamento da verificação da etapa 1: verificacao/verificacao_6/etapa1/planejamento_entrega1.md
          - Verificação dos artefatos da etapa 1: verificacao/verificacao_6/etapa1/verificacao_entrega1.md
        - Etapa 2:
          - Planejamento da verificação da etapa 2: verificacao/verificacao_6/etapa2/planejamento_entrega2.md
          - Verificação dos artefatos da etapa 2: verificacao/verificacao_6/etapa2/verificacao_entrega2.md
        - Etapa 3:
          - Planejamento da verificação da etapa 3: verificacao/verificacao_6/etapa3/planejamento_entrega3.md
          - Verificação dos artefatos da etapa 3: verificacao/verificacao_6/etapa3/verificacao_entrega3.md
        - Etapa 4:
          - Planejamento da verificação da etapa 4: verificacao/verificacao_6/etapa4/planejamento_entrega4.md
          - Verificação dos artefatos da etapa 4: verificacao/verificacao_6/etapa4/verificacao_entrega4.md
        - Etapa 5:
          - Planejamento da verificação da etapa 5: verificacao/verificacao_6/etapa5/planejamento_entrega5.md
          - Verificação dos artefatos da etapa 5: verificacao/verificacao_6/etapa5/verificacao_entrega5.md
    - Apresentações: apresentacoes.md
    - Manual de Escrita: manual.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Tema claro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: lime
      toggle:
        icon: material/brightness-4
        name: Tema escuro
