site_name: 2023.1-Alistamento
site_url: https://interacao-humano-computador.github.io/2023.1-Alistamento/
repo_name: 2023.1-Alistamento
repo_url: https://github.com/Interacao-Humano-Computador/2023.1-Alistamento/
nav:
    - Home: index.md
    - Atas de Reunião:
      - Ata 1: atas/ata1.md
      - Ata 2: atas/ata2.md
    - Planejamento:
      - Cronograma inicial: planejamento/cronograma.md
      - Cronograma realizado: planejamento/cronograma_real.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Sites avaliados: planejamento/sites_avaliados.md
      - Avaliação dos sites:
        - Escola de Música: planejamento/avaliacoes/escola.md
        - Alistamento Militar: planejamento/avaliacoes/alistamento.md
        - Shopee: planejamento/avaliacoes/shopee.md
        - Striker: planejamento/avaliacoes/striker.md
      - Processo de design: planejamento/processo_design.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Tema claro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Tema escuro
